# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r5CxywVdbwcp5lP-Zn9nN1pqhOnjj8V_
"""

def saudacao(nome):
  print("Ola", nome)

nome = input("Entre seu nome: ")

saudacao(nome)

def alterna(n):
 x = 1
 for i in range (n + 1):
    print(i * x, end =" ")
    x *= -1
num = int(input("Qual e o numero: "))
alterna(num)

def p_retangulo(base, altura):
  p = base * altura / 2
  return p

def saudacao(nome, mensagem):
  print("Ola", nome, "\b", mensagem)

saudacao("Joao", "Como voce esta?")

saudacao(mensagem="Tudo bem?", nome="Maria" )

def calcular_valores(numero):
  triplo = numero * 3
  quadruplo = numero * 4
  quinta_potencia = numero ** 5
  return triplo, quadruplo, quinta_potencia

resultado = calcular_valores(2)
print(resultado)

triplo, quadruplo, quinta_potencia = calcular_valores(3)
print(triplo)
print(quadruplo)
print(quinta_potencia)

def soma_pn(valores):
  soma_p = 0
  soma_n = 0
  for n in valores:
    if n > 0:
      soma_p += n
    else:
      soma_n += n
  return soma_p, soma_n

valores= [2, -1, 3, -4]
soma_p, soma_n = soma_pn(valores)
print(f"soma dos positivos = {soma_p}\nsoma dos negativos = {soma_n}")

def teste(a, b):
  return a + b, a * b

res = teste(2, 3)
res1, res2 = teste(2, 3)
print(res)
print(f"res1 = {res1}, res2 = {res2}")

def somas(lista):
  soma, soma2 = 0, 0
  for num in lista:
    soma = soma + num
    soma2 = soma2 + num * num
  return soma, soma2

L = [1, 2, 3]
x1, x2 = somas(L)
print(f"soma = {x1}; soma ao quadrado = {x2}")